from __future__ import annotations

from typing import Any

from .business_qa_types import BusinessQaCase


LCBusinessQaCase = BusinessQaCase


LC_BUSINESS_QA_CASES: tuple[LCBusinessQaCase, ...] = (
    LCBusinessQaCase(
        case_id="LC-QA-001-bank-status",
        level="L1",
        question="可接受银行台账里的 Bank Status 有哪些状态？Removed 和 Not Involved 分别在什么场景使用？",
        expected_behavior="说明 Bank Status 与台账/查询相关，并区分有证据和证据不足内容。",
        expected_answer_points=[
            "Bank Status 是台账或查询相关字段/状态。",
            "应覆盖当前证据中出现的状态，例如 Normal(New)、Removed、Not Involved。",
            "Removed / Not Involved 的场景必须以台账或规则证据为准。",
            "证据不足时不得扩展状态含义。",
        ],
        expected_entities=["Bank Status", "Removed", "Not Involved"],
        expected_relations=["HasReportFilter"],
        expected_domains=["MonitoringReport"],
        expected_sections=["report_rule"],
        expected_evidence_keywords=["Bank Status", "Removed", "Not Involved"],
        forbidden_claims=["自动关闭账户", "监管黑名单"],
        must_not_do=["不得编造 Bank Status 状态含义。"],
        grading_notes="LC mini graph 直接覆盖 Bank Status 和 report_rule，状态枚举只按 evidence 判定。",
        expected_graph_coverage="partial",
    ),
    LCBusinessQaCase(
        case_id="LC-QA-002-default-task",
        level="L1",
        question="系统什么时候会生成 Please confirm the default of Acceptance Bank[Bank Name] 待办？Current Handler 是谁？",
        expected_behavior="识别 Workflow/task_rule，并说明待办、处理人和证据来源。",
        expected_answer_points=[
            "这是 Workflow / task_rule 相关问题。",
            "需要说明 Please confirm the default of Acceptance Bank 待办的生成场景。",
            "需要说明 Current Handler 或目标处理人的关系。",
            "不得编造额外审批流。",
        ],
        expected_entities=[
            "Bank Default Confirmation",
            "Current Handler",
        ],
        expected_relations=["AssignsHandler"],
        expected_domains=["Workflow"],
        expected_sections=["task_rule"],
        expected_evidence_keywords=[
            "Please confirm the default",
            "Current Handler",
            "Bank Default Confirmation",
        ],
        forbidden_claims=["多级会签", "总行自动审批"],
        must_not_do=["不得编造审批链路。"],
        grading_notes="LC mini graph 覆盖 Bank Default Confirmation -> Current Handler。",
        expected_graph_coverage="full",
    ),
    LCBusinessQaCase(
        case_id="LC-QA-003-transfer-to",
        level="L2",
        question="Transfer To 对 Bank Default Confirmation 的维护权限有什么影响？",
        expected_behavior="解释 Transfer To 与当前处理人/维护权限的关系；证据不足时应说明不足。",
        expected_answer_points=[
            "Transfer To 与待办转审、当前处理人或维护权限有关。",
            "Bank Default Confirmation 的维护权限应基于 task_rule / permission evidence 表述。",
            "只能说当前证据支持的内容，不得写成 Confirmed graph fact。",
        ],
        expected_entities=["Transfer To", "Bank Default Confirmation", "Current Handler"],
        expected_relations=["TransfersTask", "HasPermission"],
        expected_domains=["Workflow"],
        expected_sections=["task_rule"],
        expected_evidence_keywords=["Transfer To", "Bank Default Confirmation", "Current Handler"],
        forbidden_claims=["永久授权", "无需权限校验"],
        must_not_do=["不得把候选证据当正式权限矩阵。"],
        grading_notes="LC mini graph 对 Transfer To 覆盖有限，评测应允许 partial/inconclusive。",
        expected_graph_coverage="partial",
    ),
    LCBusinessQaCase(
        case_id="LC-QA-004-integration-fields",
        level="L1",
        question="eflowNum 和 Suggested Rating 在可接受银行流程中分别是什么作用？",
        expected_behavior="识别 Integration/api_desc，分别说明接口字段作用和证据不足项。",
        expected_answer_points=[
            "eflowNum 是电子流或接口编号类字段。",
            "Suggested Rating 与外部风险认证或评级建议相关。",
            "不得编造接口 URL 或外部系统名。",
            "每个结论需要引用接口证据。",
        ],
        expected_entities=["Risk Certification API", "eflowNum", "Suggested Rating"],
        expected_relations=["CallsBackendApi"],
        expected_domains=["Integration"],
        expected_sections=["api_desc"],
        expected_evidence_keywords=["eflowNum", "Suggested Rating", "接口"],
        forbidden_claims=["REST URL", "Kafka topic", "第三方系统名称"],
        must_not_do=["不得编造接口 URL 或系统名。"],
        grading_notes="LC mini graph 覆盖 eflowNum，Suggested Rating 可能只由文本 evidence 支持。",
        expected_graph_coverage="partial",
    ),
    LCBusinessQaCase(
        case_id="LC-QA-005-swift-internal-code",
        level="L2",
        question="回顾电子流里 Swift Code 和 Bank Internal Code 的修改规则有什么区别？",
        expected_behavior="区分 Swift Code / Bank Internal Code，证据不足时明确不足。",
        expected_answer_points=[
            "Swift Code / Bank Internal Code 都是字段或主数据标识。",
            "需要说明二者在回顾电子流中的可修改性差异。",
            "若证据不足，应明确说明当前证据不足。",
            "不得混淆 Swift Code 与 Bank Internal Code。",
        ],
        expected_entities=["Swift Code", "Bank Internal Code"],
        expected_relations=[],
        expected_domains=["MasterData", "Workflow"],
        expected_sections=["field_table", "business_rule"],
        expected_evidence_keywords=["Swift Code", "Bank Internal Code"],
        forbidden_claims=["两者完全相同", "无需审批即可修改"],
        must_not_do=["不得混淆两个字段。"],
        grading_notes="LC mini graph 对该问题覆盖有限，应允许 inconclusive。",
        expected_graph_coverage="partial",
    ),
    LCBusinessQaCase(
        case_id="LC-QA-006-migration-dry-run",
        level="L1",
        question="历史数据迁移中的 dry-run 主要用于验证什么？和 Swift Code 有什么关系？",
        expected_behavior="识别 DataMigrationInitialization / dfx_rule，区分 dry-run 与 Swift Code evidence。",
        expected_answer_points=[
            "dry-run 用于迁移前验证或试运行。",
            "是否涉及 Swift Code 必须根据 evidence 判断。",
            "不得编造迁移脚本或底表名。",
            "需要引用 migration evidence。",
        ],
        expected_entities=["Historical Data Migration", "dry-run", "Swift Code"],
        expected_relations=["HasRuleAtom"],
        expected_domains=["DataMigrationInitialization"],
        expected_sections=["dfx_rule"],
        expected_evidence_keywords=["dry-run", "历史数据迁移", "Swift Code"],
        forbidden_claims=["具体脚本名称", "底表名", "定时任务名称"],
        must_not_do=["不得编造迁移脚本或底表。"],
        grading_notes="LC mini graph 覆盖 Historical Data Migration -> dry-run，Swift Code 为 partial。",
        expected_graph_coverage="partial",
    ),
    LCBusinessQaCase(
        case_id="LC-QA-007-report-ledger",
        level="L2",
        question="可接受银行查询/报表能力会读取哪些台账字段或状态？它和 Bank Status 有什么关系？",
        expected_behavior="识别 MonitoringReport / Ledger，并表达查询条件、报表字段与 Bank Status 的关系。",
        expected_answer_points=[
            "应识别查询/报表能力与 Ledger / MonitoringReport 有关。",
            "Bank Status 可作为查询条件或报表相关字段。",
            "应表达 HasReportFilter / HasReportColumn / ReadsLedger 这类关系。",
            "需要引用 report_rule evidence。",
        ],
        expected_entities=["Acceptable Bank Ledger Search", "Bank Status"],
        expected_relations=["HasReportFilter"],
        expected_domains=["MonitoringReport"],
        expected_sections=["report_rule"],
        expected_evidence_keywords=["Bank Status", "查询", "报表"],
        forbidden_claims=["自动生成监管报送"],
        must_not_do=["不得扩展到未出现的报表。"],
        grading_notes="LC mini graph 覆盖 Acceptable Bank Ledger Search -> Bank Status。",
        expected_graph_coverage="full",
    ),
    LCBusinessQaCase(
        case_id="LC-QA-008-access-audit",
        level="L1",
        question="可接受银行相关操作有哪些权限或审计要求？如果证据不足应该如何回答？",
        expected_behavior="识别 AccessAudit 证据，区分有证据和不确定项。",
        expected_answer_points=[
            "应识别 AccessAudit 相关信息。",
            "应说明 AuditLog / OperationLog / Data Scope 中有证据支持的项。",
            "证据不足时不得编造权限矩阵。",
            "需要引用 AccessAudit evidence。",
        ],
        expected_entities=["Acceptable Bank Audit Log", "OperationLog"],
        expected_relations=["WritesOperationLog"],
        expected_domains=["AccessAudit"],
        expected_sections=["task_rule"],
        expected_evidence_keywords=["AuditLog", "OperationLog", "Data Scope"],
        forbidden_claims=["完整权限矩阵", "所有角色列表"],
        must_not_do=["不得编造权限矩阵。"],
        grading_notes="LC mini graph 覆盖 Acceptable Bank Audit Log -> OperationLog。",
        expected_graph_coverage="full",
    ),
    LCBusinessQaCase(
        case_id="LC-QA-009-version-review",
        level="L2",
        question="如果历史 US 和后续 US 对同一个可接受银行台账规则描述不一致，Agent 应如何判断当前有效规则？",
        expected_behavior="说明需要 latestFlag / supersedes / versionStatus / source evidence，无法判断时人工确认。",
        expected_answer_points=[
            "应基于 latestFlag / supersedes / versionStatus / source evidence 判断。",
            "无法判断最新规则时应进入人工确认。",
            "不得硬判当前有效规则。",
            "这是 version review 触发场景。",
        ],
        expected_entities=[],
        expected_relations=["HasVersion"],
        expected_domains=["Ledger", "RuleManagement"],
        expected_sections=["business_rule", "dfx_rule"],
        expected_evidence_keywords=["latestFlag", "supersedes", "versionStatus"],
        forbidden_claims=["无条件以后出现的 US 为准"],
        must_not_do=["不得硬判最新规则。"],
        grading_notes="若无明确 supersedes 证据，应基于 HasVersion 和 source evidence 输出待确认。",
        expected_graph_coverage="partial",
    ),
    LCBusinessQaCase(
        case_id="LC-QA-010-impact-bank-status",
        level="L2",
        question="如果 Bank Status 的含义或取值发生变化，可能影响哪些功能维度？",
        expected_behavior="区分 evidence 支持的影响和可能影响，不能把无证据推断当确定事实。",
        expected_answer_points=[
            "应覆盖台账、查询/报表、字段规则、状态规则、可能的权限/审计、迁移数据。",
            "必须区分有证据支持与可能影响。",
            "应引用 evidence。",
            "不得把无证据推断当确定事实。",
        ],
        expected_entities=["Bank Status"],
        expected_relations=["HasReportFilter"],
        expected_domains=["MonitoringReport", "DataMigrationInitialization", "AccessAudit"],
        expected_sections=["report_rule", "dfx_rule", "task_rule"],
        expected_evidence_keywords=["Bank Status", "dry-run", "OperationLog"],
        forbidden_claims=["所有模块都会失败", "自动触发清算"],
        must_not_do=["不得把可能影响写成确定事实。"],
        grading_notes="LC mini graph 仅局部覆盖，综合影响应判 partial。",
        expected_graph_coverage="partial",
    ),
)


def default_lc_business_qa_cases() -> list[LCBusinessQaCase]:
    return list(LC_BUSINESS_QA_CASES)


def serialize_lc_business_qa_case(case: LCBusinessQaCase) -> dict[str, Any]:
    return {
        "case_id": case.case_id,
        "level": case.level,
        "question": case.question,
        "expected_behavior": case.expected_behavior,
        "expected_answer_points": list(case.expected_answer_points),
        "expected_entities": list(case.expected_entities),
        "expected_relations": list(case.expected_relations),
        "expected_domains": list(case.expected_domains),
        "expected_sections": list(case.expected_sections),
        "expected_evidence_keywords": list(case.expected_evidence_keywords),
        "expected_source_us_ids": list(case.expected_source_us_ids),
        "forbidden_claims": list(case.forbidden_claims),
        "must_not_do": list(case.must_not_do),
        "grading_notes": case.grading_notes,
        "expected_graph_coverage": case.expected_graph_coverage,
    }


__all__ = [
    "LCBusinessQaCase",
    "LC_BUSINESS_QA_CASES",
    "default_lc_business_qa_cases",
    "serialize_lc_business_qa_case",
]
