from __future__ import annotations

from typing import Any

from .us_generation_types import USGenerationCase


LC_US_GENERATION_CASES: tuple[USGenerationCase, ...] = (
    USGenerationCase(
        case_id="LC-USGEN-001-bank-status",
        module_name="LC",
        case_pack_name="LC_US_GENERATION",
        level="L1",
        user_request="请基于现有可接受银行台账知识，生成一条关于 Bank Status 取值展示和查询条件优化的迭代 US。",
        generation_task_type="ITERATION_US",
        expected_us_sections=[
            "role_goal_value",
            "given_when_then",
            "field_specs",
            "business_rules",
            "report_query",
            "acceptance_criteria",
            "source_evidence",
        ],
        expected_entities=["Bank Status", "Removed", "Not Involved"],
        expected_relations=["HasReportFilter", "HasStateTransition"],
        expected_domains=["Ledger", "MonitoringReport"],
        expected_sections=["report_rule", "field_table"],
        expected_evidence_keywords=["Bank Status", "Removed", "Not Involved"],
        forbidden_claims=["监管黑名单", "自动关闭账户"],
        must_not_do=["不得无证据新增状态。"],
        grading_notes="应引用 Bank Status 和状态枚举 evidence；证据不足项进入待确认。",
        graph_coverage_expectation="full",
    ),
    USGenerationCase(
        case_id="LC-USGEN-002-default-task",
        module_name="LC",
        case_pack_name="LC_US_GENERATION",
        level="L1",
        user_request="请生成一条关于每月生成可接受银行出险确认待办的 US，要求包含待办名称、Current Handler 和防重逻辑。",
        generation_task_type="TASK_WORKFLOW_US",
        expected_us_sections=[
            "role_goal_value",
            "given_when_then",
            "task_rules",
            "business_rules",
            "access_audit",
            "acceptance_criteria",
            "source_evidence",
        ],
        expected_entities=["Bank Default Confirmation", "Current Handler"],
        expected_relations=["AssignsHandler"],
        expected_domains=["Workflow"],
        expected_sections=["task_rule"],
        expected_evidence_keywords=["Please confirm the default", "Current Handler"],
        forbidden_claims=["多级会签", "总行自动审批"],
        must_not_do=["不得编造审批流。"],
        grading_notes="应体现待办生成、处理人和候选级 source evidence。",
        graph_coverage_expectation="full",
    ),
    USGenerationCase(
        case_id="LC-USGEN-003-transfer-to",
        module_name="LC",
        case_pack_name="LC_US_GENERATION",
        level="L2",
        user_request="请生成一条关于 Bank Default Confirmation 待办转审 Transfer To 的迭代 US，重点说明维护权限如何变化。",
        generation_task_type="TASK_WORKFLOW_US",
        expected_us_sections=[
            "role_goal_value",
            "given_when_then",
            "task_rules",
            "access_audit",
            "business_rules",
            "acceptance_criteria",
            "source_evidence",
        ],
        expected_entities=["Transfer To", "Bank Default Confirmation", "Current Handler"],
        expected_relations=["TransfersTask", "HasPermission"],
        expected_domains=["Workflow"],
        expected_sections=["task_rule"],
        expected_evidence_keywords=["Transfer To", "Bank Default Confirmation", "Current Handler"],
        forbidden_claims=["永久授权", "无需权限校验"],
        must_not_do=["不得把无证据权限规则写成确定事实。"],
        grading_notes="应说明转审后维护权限转移和当前处理人变化。",
        graph_coverage_expectation="full",
    ),
    USGenerationCase(
        case_id="LC-USGEN-004-risk-integration",
        module_name="LC",
        case_pack_name="LC_US_GENERATION",
        level="L1",
        user_request="请基于现有知识生成一条关于可接受银行外部风险认证接口回传 eflowNum 和 Suggested Rating 的 US。",
        generation_task_type="INTEGRATION_US",
        expected_us_sections=[
            "role_goal_value",
            "given_when_then",
            "api_integration",
            "field_specs",
            "business_rules",
            "dfx",
            "acceptance_criteria",
            "source_evidence",
        ],
        expected_entities=["Risk Certification API", "eflowNum", "Suggested Rating"],
        expected_relations=["CallsBackendApi"],
        expected_domains=["Integration"],
        expected_sections=["api_desc", "field_table"],
        expected_evidence_keywords=["eflowNum", "Suggested Rating"],
        forbidden_claims=["REST URL", "Kafka topic", "第三方系统名称"],
        must_not_do=["不得编造接口 URL、底表或外部系统名。"],
        grading_notes="应说明接口字段作用，异常处理证据不足时待确认。",
        graph_coverage_expectation="full",
    ),
    USGenerationCase(
        case_id="LC-USGEN-005-swift-internal-code",
        module_name="LC",
        case_pack_name="LC_US_GENERATION",
        level="L2",
        user_request="请生成一条关于回顾电子流中 Swift Code 与 Bank Internal Code 可修改性规则的 US。",
        generation_task_type="FIELD_CHANGE_US",
        expected_us_sections=[
            "role_goal_value",
            "given_when_then",
            "field_specs",
            "business_rules",
            "acceptance_criteria",
            "source_evidence",
        ],
        expected_entities=["Swift Code", "Bank Internal Code"],
        expected_relations=["DependsOn"],
        expected_domains=["MasterData", "Workflow"],
        expected_sections=["field_table", "business_rule"],
        expected_evidence_keywords=["Swift Code", "Bank Internal Code"],
        forbidden_claims=["两者完全相同", "无需审批即可修改"],
        must_not_do=["不得混淆两个字段。"],
        grading_notes="应区分 Swift Code 和 Bank Internal Code 的可修改性差异。",
        graph_coverage_expectation="full",
    ),
    USGenerationCase(
        case_id="LC-USGEN-006-migration-dry-run",
        module_name="LC",
        case_pack_name="LC_US_GENERATION",
        level="L1",
        user_request="请生成一条关于可接受银行历史数据迁移 dry-run 验证的 US，关注迁移前校验和 Swift Code 相关风险。",
        generation_task_type="MIGRATION_US",
        expected_us_sections=[
            "role_goal_value",
            "given_when_then",
            "migration",
            "field_specs",
            "dfx",
            "acceptance_criteria",
            "source_evidence",
        ],
        expected_entities=["Historical Data Migration", "dry-run", "Swift Code"],
        expected_relations=["HasRuleAtom", "MapsSourceToTarget"],
        expected_domains=["DataMigrationInitialization"],
        expected_sections=["migration_rule", "dfx_rule"],
        expected_evidence_keywords=["dry-run", "Swift Code"],
        forbidden_claims=["具体脚本名称", "底表名"],
        must_not_do=["不得编造迁移脚本或底表。"],
        grading_notes="应说明 dry-run 是迁移前验证，Swift Code 风险需基于证据。",
        graph_coverage_expectation="full",
    ),
    USGenerationCase(
        case_id="LC-USGEN-007-access-audit",
        module_name="LC",
        case_pack_name="LC_US_GENERATION",
        level="L1",
        user_request="请生成一条关于可接受银行操作权限和审计记录的 US，要求对证据不足的权限矩阵保持谨慎。",
        generation_task_type="RULE_OPTIMIZATION_US",
        expected_us_sections=[
            "role_goal_value",
            "given_when_then",
            "access_audit",
            "business_rules",
            "dfx",
            "acceptance_criteria",
            "source_evidence",
        ],
        expected_entities=["Acceptable Bank Audit Log", "OperationLog", "Data Scope"],
        expected_relations=["WritesOperationLog", "HasPermission"],
        expected_domains=["AccessAudit"],
        expected_sections=["task_rule", "field_table"],
        expected_evidence_keywords=["AuditLog", "OperationLog", "Data Scope"],
        forbidden_claims=["完整权限矩阵", "所有角色列表"],
        must_not_do=["不得编造完整权限矩阵。"],
        grading_notes="应说明权限、Data Scope、AuditLog、OperationLog 的证据情况。",
        graph_coverage_expectation="full",
    ),
    USGenerationCase(
        case_id="LC-USGEN-008-version-uncertain",
        module_name="LC",
        case_pack_name="LC_US_GENERATION",
        level="L2",
        user_request="如果历史 US 和后续 US 对同一台账规则描述不一致，请生成一条用于处理版本不确定场景的 US。",
        generation_task_type="VERSION_REVIEW_US",
        expected_us_sections=[
            "role_goal_value",
            "given_when_then",
            "business_rules",
            "acceptance_criteria",
            "source_evidence",
        ],
        expected_entities=[],
        expected_relations=["HasVersion"],
        expected_domains=["RuleManagement"],
        expected_sections=["business_rule", "dfx_rule"],
        expected_evidence_keywords=["latestFlag", "supersedes", "versionStatus"],
        forbidden_claims=["无条件以后出现的 US 为准"],
        must_not_do=["不得硬判最新规则。"],
        grading_notes="若无明确 Supersedes 证据，应使用 HasVersion 和 source evidence 输出待确认，不硬判最新规则。",
        graph_coverage_expectation="partial",
    ),
)


def default_lc_us_generation_cases() -> list[USGenerationCase]:
    return list(LC_US_GENERATION_CASES)


def serialize_lc_us_generation_case(case: USGenerationCase) -> dict[str, Any]:
    return {
        "case_id": case.case_id,
        "module_name": case.module_name,
        "case_pack_name": case.case_pack_name,
        "level": case.level,
        "user_request": case.user_request,
        "generation_task_type": case.generation_task_type,
        "expected_us_sections": list(case.expected_us_sections),
        "expected_entities": list(case.expected_entities),
        "expected_relations": list(case.expected_relations),
        "expected_domains": list(case.expected_domains),
        "expected_sections": list(case.expected_sections),
        "expected_evidence_keywords": list(case.expected_evidence_keywords),
        "forbidden_claims": list(case.forbidden_claims),
        "must_not_do": list(case.must_not_do),
        "grading_notes": case.grading_notes,
        "graph_coverage_expectation": case.graph_coverage_expectation,
    }


__all__ = [
    "LC_US_GENERATION_CASES",
    "default_lc_us_generation_cases",
    "serialize_lc_us_generation_case",
]
