from __future__ import annotations

from typing import Any, Protocol

from .sidecar_registry_types import IngestionBatchRecord, SidecarPersistenceBundle


class SidecarRepository(Protocol):
    def initialize_schema(self) -> None: ...
    def begin_batch(self, batch: IngestionBatchRecord) -> None: ...
    def persist_bundle(self, bundle: SidecarPersistenceBundle) -> None: ...
    def complete_batch(self, batch_id: str, summary: dict[str, Any]) -> None: ...
    def fail_batch(self, batch_id: str, error: dict[str, Any]) -> None: ...
    def get_document(self, document_id: str) -> dict[str, Any] | None: ...
    def get_document_version(self, document_version_id: str) -> dict[str, Any] | None: ...
    def get_batch(self, batch_id: str) -> dict[str, Any] | None: ...
    def list_source_text_units(self, document_version_id: str) -> list[dict[str, Any]]: ...
    def list_semantic_objects(self, document_version_id: str) -> list[dict[str, Any]]: ...
    def list_semantic_relations(self, document_version_id: str) -> list[dict[str, Any]]: ...
    def list_evidence_for_object(self, semantic_object_id: str) -> list[dict[str, Any]]: ...
    def list_issues(self, document_version_id: str) -> list[dict[str, Any]]: ...
    def get_rollback_manifest(self, batch_id: str) -> list[dict[str, Any]]: ...
    def validate_referential_integrity(self) -> dict[str, Any]: ...
    def apply_lifecycle_migration(self) -> None: ...
    def set_document_active_version(self, document_id: str, active_document_version_id: str | None, batch_id: str) -> None: ...
    def get_active_version(self, document_id: str) -> dict[str, Any] | None: ...
    def update_document_version_status(self, document_version_id: str, status: str) -> None: ...
    def record_version_state(self, document_version_id: str, old_status: str | None, new_status: str, batch_id: str, reason_code: str) -> None: ...
    def upsert_raw_chunk_contribution(self, item: dict[str, Any]) -> None: ...
    def upsert_semantic_object_contribution(self, item: dict[str, Any]) -> None: ...
    def upsert_semantic_relation_contribution(self, item: dict[str, Any]) -> None: ...
    def deactivate_version_contributions(self, document_version_id: str, batch_id: str) -> None: ...
    def active_chunk_contribution_count(self, chunk_id: str) -> int: ...
    def active_object_contribution_count(self, semantic_object_id: str) -> int: ...
    def active_relation_contribution_count(self, semantic_relation_id: str) -> int: ...
